import { NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { sessionStateSchema } from '@/lib/validation/qbank';
import { apiError, assertMutationRequest, readJson, enforceRateLimit } from '@/lib/server/api';
export async function GET(_request:Request,{params}:{params:Promise<{sessionId:string}>}){try{const {sessionId}=await params;const url=new URL(_request.url);const position=Number(url.searchParams.get('position')??'1');const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return NextResponse.json({error:'unauthorized'},{status:401});const {data,error}=await supabase.rpc('get_study_session_state',{p_session_id:sessionId,p_position:position});if(error){const code=error.message.includes('block_closed')?'block_closed':error.message.includes('block_not_open')?'block_not_open':error.message.includes('session_expired')?'session_expired':error.message.includes('on_break')?'on_break':'session_not_found';const status=code==='session_expired'?410:code==='session_not_found'?404:409;return NextResponse.json({error:code},{status});}return NextResponse.json(data??null,{headers:{'Cache-Control':'private,no-store'}});}catch(error){return apiError(error,'session_load_failed');}}
export async function POST(request:Request,{params}:{params:Promise<{sessionId:string}>}){
 const blocked=assertMutationRequest(request);if(blocked)return blocked;
 try{const {sessionId}=await params;const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return NextResponse.json({error:'unauthorized'},{status:401});await enforceRateLimit(supabase,'qbank_answer',120,60);const p=sessionStateSchema.parse(await readJson(request));const {error}=await supabase.rpc('set_study_session_item_state',{p_session_id:sessionId,p_position:p.position,p_marked:p.marked??null,p_note:p.note??null});if(error){const msg=error.message; const code=msg.includes('block_closed')?'block_closed':msg.includes('block_not_open')?'block_not_open':msg.includes('on_break')?'on_break':msg.includes('session_not_active')?'session_not_active':'state_update_failed'; return NextResponse.json({error:code},{status:code==='block_closed'||code==='block_not_open'||code==='on_break'?409:400});}return NextResponse.json({ok:true},{headers:{'Cache-Control':'no-store'}});}catch(error){return apiError(error,'state_update_failed');}
}
