import { createClient } from '@/lib/supabase/server';
import { SignOutButton } from '@/components/auth/sign-out-button';
import { ExamSelector } from '@/components/account/exam-selector';
import { getI18n } from '@/lib/i18n/server';
import { DeleteAccountButton } from '@/components/account/delete-account-button';
import { LeaderboardPrivacy } from '@/components/account/leaderboard-privacy';
export default async function SettingsPage() { const { messages: m } = await getI18n(); const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user)
    return null; const [{ data: profile }, { data: exams }] = await Promise.all([supabase.from('profiles').select('full_name,role,active_exam_id,leaderboard_visible').eq('id', user.id).maybeSingle(), supabase.from('exams').select('id,code,name').order('name')]); return <div className="page"><div className="page-head"><div><div className="eyebrow">{m.settings.eyebrow}</div><h1>{m.settings.title}</h1><p className="subtitle">{m.settings.subtitle}</p></div></div><div className="grid grid-3"><section className="card card-pad"><div className="kicker">{m.settings.identity}</div><h2 className="section-heading">{m.settings.profile}</h2><p className="panel-sub">{profile?.full_name || m.settings.nameNotSet}</p><p className="panel-sub field-note">{user.email}</p><p className="panel-sub field-note">{m.settings.role}: {profile?.role ?? 'student'}</p></section><section className="card card-pad"><div className="kicker">{m.settings.exam}</div><h2 className="section-heading">{m.settings.activeExam}</h2><ExamSelector exams={exams ?? []} current={profile?.active_exam_id ?? null}/></section><section className="card card-pad"><div className="kicker">{m.settings.session}</div><h2 className="section-heading">{m.settings.signOut}</h2><p className="panel-sub field-note-bottom">{m.settings.endSession}</p><SignOutButton /></section></div><section className="card card-pad settings-danger-card"><div className="kicker">Privacy</div><h2 className="section-heading">Account deletion</h2><p className="panel-sub">Permanently remove your account and associated learning records.</p><DeleteAccountButton /></section></div>; }

