import Link from 'next/link';
import { createClient } from '@/lib/supabase/server';
import { getI18n } from '@/lib/i18n/server';

export default async function ExamGuidePage() {
  const { locale } = await getI18n();
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return null;
  const { data: profile } = await supabase.from('profiles').select('active_exam_id').eq('id', user.id).maybeSingle();
  const { data: exam } = profile?.active_exam_id ? await supabase.from('exams').select('id,code,name').eq('id', profile.active_exam_id).maybeSingle() : { data: null };
  const imle = String(exam?.code ?? '').toUpperCase() === 'IMLE';
  const copy = {
    en: { eyebrow:'Exam guide', title: imle?'Israeli Medical Licensing Exam (IMLE)':'Your exam guide', sub:imle?'Keep the official exam structure, core subjects and your MDvoro preparation tools in one place.':'Exam structure and preparation guidance are driven by the active exam profile configured in MDvoro.', structure:'Official structure', part:'Part', duration:'2.5 hours', extra:'Extra time', questions:'210 questions', noBreak:'No break between the two parts', subjects:'Core subjects', books:'Core reference books published by IMA', tools:'MDvoro preparation path', start:'Start practice', simulation:'Full simulation', plan:'Build my plan', source:'Official reference', sourceText:'Always verify dates, editions and exam notices against the current official IMA / Ministry of Health publication.', subjectsList:['Pediatrics','Surgery','Internal Medicine','Psychiatry','Obstetrics & Gynecology'], booksList:[['Psychiatry',"Kaplan & Sadock’s Synopsis of Psychiatry, 12th ed."],['Internal Medicine','Harrison, 22nd ed. from summer 2026'],['Surgery','Sabiston, 21st ed.'],['Pediatrics','Nelson, 22nd ed. from summer 2025'],['Obstetrics & Gynecology','Current Diagnosis & Treatment Obstetrics & Gynecology, 12th ed.']] },
    he: { eyebrow:'מדריך הבחינה', title:imle?'בחינת הרישוי הישראלית (IMLE)':'מדריך הבחינה שלך', sub:imle?'מבנה הבחינה, המקצועות וכלי ההכנה של MDvoro במקום אחד.':'מבנה הבחינה וההכנה נקבעים לפי פרופיל הבחינה הפעיל ב‑MDvoro.', structure:'מבנה רשמי', part:'חלק', duration:'שעתיים וחצי', extra:'תוספת זמן', questions:'210 שאלות', noBreak:'אין הפסקה בין שני החלקים', subjects:'המקצועות המרכזיים', books:'ספרי העיון המופיעים באתר ההסתדרות הרפואית', tools:'מסלול ההכנה ב‑MDvoro', start:'התחל תרגול', simulation:'סימולציה מלאה', plan:'בנה תוכנית', source:'מקור רשמי', sourceText:'יש לאמת תמיד מועדים, מהדורות והודעות בחינה מול הפרסום הרשמי העדכני של הר״י / משרד הבריאות.', subjectsList:['רפואת ילדים','כירורגיה','רפואה פנימית','פסיכיאטריה','יילוד וגינקולוגיה'], booksList:[['פסיכיאטריה',"Kaplan & Sadock’s Synopsis of Psychiatry, מהדורה 12"],['רפואה פנימית','Harrison, מהדורה 22 החל מקיץ 2026'],['כירורגיה','Sabiston, מהדורה 21'],['ילדים','Nelson, מהדורה 22 החל מקיץ 2025'],['יילוד וגינקולוגיה','Current Diagnosis & Treatment Obstetrics & Gynecology, מהדורה 12']] },
    ar: { eyebrow:'دليل الامتحان', title:imle?'امتحان الترخيص الطبي الإسرائيلي (IMLE)':'دليل امتحانك', sub:imle?'هيكل الامتحان والمواد الأساسية ومسار الاستعداد في MDvoro في مكان واحد.':'هيكل الامتحان وإرشادات التحضير تعتمد على ملف الامتحان النشط في MDvoro.', structure:'الهيكل الرسمي', part:'القسم', duration:'ساعتان ونصف', extra:'وقت إضافي', questions:'210 أسئلة', noBreak:'لا توجد استراحة بين القسمين', subjects:'المواد الأساسية', books:'المراجع الأساسية المنشورة من الجمعية الطبية الإسرائيلية', tools:'مسار التحضير في MDvoro', start:'ابدأ التدريب', simulation:'محاكاة كاملة', plan:'أنشئ خطتي', source:'المرجع الرسمي', sourceText:'تحقق دائمًا من المواعيد والطبعات وإعلانات الامتحان من المنشورات الرسمية الحالية للجمعية الطبية / وزارة الصحة.', subjectsList:['طب الأطفال','الجراحة','الطب الباطني','الطب النفسي','النسائية والتوليد'], booksList:[['الطب النفسي',"Kaplan & Sadock’s Synopsis of Psychiatry، الطبعة 12"],['الطب الباطني','Harrison، الطبعة 22 من صيف 2026'],['الجراحة','Sabiston، الطبعة 21'],['طب الأطفال','Nelson، الطبعة 22 من صيف 2025'],['النسائية والتوليد','Current Diagnosis & Treatment Obstetrics & Gynecology، الطبعة 12']] },
    ru: { eyebrow:'Гид по экзамену', title:imle?'Израильский экзамен на медицинскую лицензию (IMLE)':'Ваш гид по экзамену', sub:imle?'Структура, основные дисциплины и путь подготовки в MDvoro — в одном месте.':'Структура и подготовка определяются активным профилем экзамена в MDvoro.', structure:'Официальная структура', part:'Часть', duration:'2,5 часа', extra:'Дополнительное время', questions:'210 вопросов', noBreak:'Перерыва между двумя частями нет', subjects:'Основные дисциплины', books:'Основные источники, опубликованные IMA', tools:'Маршрут подготовки MDvoro', start:'Начать практику', simulation:'Полная симуляция', plan:'Создать план', source:'Официальный источник', sourceText:'Всегда проверяйте даты, издания и объявления экзамена по актуальным официальным публикациям IMA / Минздрава.', subjectsList:['Педиатрия','Хирургия','Внутренняя медицина','Психиатрия','Акушерство и гинекология'], booksList:[['Психиатрия',"Kaplan & Sadock’s Synopsis of Psychiatry, 12-е изд."],['Внутренняя медицина','Harrison, 22-е изд. с лета 2026'],['Хирургия','Sabiston, 21-е изд.'],['Педиатрия','Nelson, 22-е изд. с лета 2025'],['Акушерство и гинекология','Current Diagnosis & Treatment Obstetrics & Gynecology, 12-е изд.']] }
  } as const;
  const t = copy[locale];
  return <div className="page"><div className="page-head"><div><div className="eyebrow">{t.eyebrow}</div><h1>{t.title}</h1><p className="subtitle">{t.sub}</p></div></div>
    {imle ? <>
      <section className="grid grid-4"><div className="card card-pad"><span className="metric-label">{t.questions}</span><strong className="metric-value">210</strong></div><div className="card card-pad"><span className="metric-label">{t.part} 1</span><strong className="metric-value">{t.duration}</strong></div><div className="card card-pad"><span className="metric-label">{t.part} 2</span><strong className="metric-value">{t.duration}</strong></div><div className="card card-pad"><span className="metric-label">{t.extra}</span><strong className="metric-value">45 min</strong><span className="metric-note">{t.noBreak}</span></div></section>
      <div className="grid grid-main" style={{ marginTop: '1rem' }}><section className="card card-pad"><div className="panel-head"><div><div className="panel-title">{t.subjects}</div></div></div><div className="chip-grid">{t.subjectsList.map(x=><span className="filter-chip selected" key={x}>{x}</span>)}</div></section><section className="card card-pad"><div className="panel-head"><div><div className="panel-title">{t.tools}</div></div></div><div className="result-review-actions compact-actions"><Link className="btn btn-primary" href="/qbank">{t.start}</Link><Link className="btn" href="/qbank?full=1">{t.simulation}</Link><Link className="btn" href="/study-plan">{t.plan}</Link></div></section></div>
      <section className="card card-pad" style={{ marginTop: '1rem' }}><div className="panel-head"><div><div className="panel-title">{t.books}</div></div></div><div className="admin-table">{t.booksList.map(([name,book])=><div className="admin-row" key={name}><div><b>{name}</b><small>{book}</small></div></div>)}</div></section>
    </> : <section className="card card-pad"><div className="panel-title">{exam?.name ?? 'Exam'}</div><p className="panel-sub">{t.sub}</p><div className="result-review-actions compact-actions"><Link className="btn btn-primary" href="/qbank">{t.start}</Link><Link className="btn" href="/study-plan">{t.plan}</Link></div></section>}
    <section className="card card-pad" style={{ marginTop: '1rem' }}><div className="panel-title">{t.source}</div><p className="panel-sub">{t.sourceText}</p>{imle && <a className="btn" href="https://www.ima.org.il/Main/TabsPage.aspx?tpId=26" target="_blank" rel="noreferrer">IMA · {t.source}</a>}</section>
  </div>;
}
