'use client';
import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { useI18n } from '@/components/i18n/provider';

type Exam={id:string;code:string;name:string};
type Catalog={topics_by_subject:{subject:string;topic:string}[];exam:{id:string;code:string;name:string;total_duration_minutes:number;max_items:number;block_duration_minutes:number;block_max_items:number;block_count:number;break_minutes:number;previous_block_review_allowed:boolean;official_max_items:number;product_max_items:number;timing_verified:boolean;timing_source:string;timing_notes:string|null};subjects:{value:string;label:string}[];topics:string[];available_questions:number};
type PoolCounts={total:number;unseen:number;answered:number;unanswered:number;incorrect:number;bookmarked:number};
type Pool='mixed'|'unseen'|'incorrect'|'answered'|'unanswered'|'bookmarked';
type ReconstructionYear={year:number;question_count:number};
const subjectLabels:Record<string,Record<string,string>>={
 'Internal Medicine':{en:'Internal Medicine',he:'רפואה פנימית',ar:'الطب الباطني',ru:'Внутренняя медицина'},
 Pediatrics:{en:'Pediatrics',he:'רפואת ילדים',ar:'طب الأطفال',ru:'Педиатрия'},
 Surgery:{en:'Surgery',he:'כירורגיה',ar:'الجراحة',ru:'Хирургия'},
 Psychiatry:{en:'Psychiatry',he:'פסיכיאטריה',ar:'الطب النفسي',ru:'Психиатрия'},
 'Obstetrics & Gynecology':{en:'Obstetrics & Gynecology',he:'מיילדות וגינקולוגיה',ar:'النسائية والتوليد',ru:'Акушерство и гинекология'},
 Anatomy:{en:'Anatomy',he:'אנטומיה',ar:'التشريح',ru:'Анатомия'},
 Physiology:{en:'Physiology',he:'פיזיולוגיה',ar:'علم وظائف الأعضاء',ru:'Физиология'},
 Biochemistry:{en:'Biochemistry',he:'ביוכימיה',ar:'الكيمياء الحيوية',ru:'Биохимия'},
 Pathology:{en:'Pathology',he:'פתולוגיה',ar:'علم الأمراض',ru:'Патология'},
 Pharmacology:{en:'Pharmacology',he:'פרמקולוגיה',ar:'علم الأدوية',ru:'Фармакология'},
 Microbiology:{en:'Microbiology',he:'מיקרוביולוגיה',ar:'علم الأحياء الدقيقة',ru:'Микробиология'},
 'Behavioral Sciences':{en:'Behavioral Sciences',he:'מדעי ההתנהגות',ar:'العلوم السلوكية',ru:'Поведенческие науки'},
 'Biostatistics & Epidemiology':{en:'Biostatistics & Epidemiology',he:'ביוסטטיסטיקה ואפידמיולוגיה',ar:'الإحصاء الحيوي وعلم الوبائيات',ru:'Биостатистика и эпидемиология'},
 Ethics:{en:'Ethics',he:'אתיקה',ar:'الأخلاقيات',ru:'Этика'}
};
export function QBankConfigurator({ exams, currentExamId, initialPool, initialExamId, fullExam=false }:{exams:Exam[];currentExamId?:string|null;initialPool?:Pool;initialExamId?:string|null;fullExam?:boolean}){
 const {messages:m,locale}=useI18n(); const router=useRouter();
 const reconstructionCopy={en:{label:'Historical reconstructions',any:'All questions',hint:'Practice a specific reconstructed exam year.'},he:{label:'שחזורים היסטוריים',any:'כל השאלות',hint:'תרגול שחזור של שנה מסוימת.'},ar:{label:'إعادات الامتحان التاريخية',any:'كل الأسئلة',hint:'تدرّب على إعادة بناء سنة محددة.'},ru:{label:'Исторические реконструкции',any:'Все вопросы',hint:'Практика реконструкции по конкретному году.'}}[locale];
 const [poolCounts,setPoolCounts]=useState<PoolCounts|null>(null); const [examId,setExamId]=useState(initialExamId??currentExamId??exams[0]?.id??''); const [catalog,setCatalog]=useState<Catalog|null>(null); const [subjects,setSubjects]=useState<string[]>([]); const [topics,setTopics]=useState<string[]>([]); const [count,setCount]=useState(20); const [mode,setMode]=useState<'practice'|'exam'>('practice'); const [pool,setPool]=useState<Pool>(initialPool??'mixed'); const [reconstructionYears,setReconstructionYears]=useState<ReconstructionYear[]>([]); const [reconstructionYear,setReconstructionYear]=useState<number|null>(null); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
 useEffect(()=>{if(!examId)return; const controller=new AbortController(); Promise.all([fetch(`/api/qbank/catalog?examId=${encodeURIComponent(examId)}`,{signal:controller.signal,cache:'no-store'}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error();return b;}),fetch(`/api/qbank/reconstruction-years?examId=${encodeURIComponent(examId)}`,{signal:controller.signal,cache:'no-store'}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error();return b as ReconstructionYear[];})]).then(([b,years])=>{setCatalog(b);setReconstructionYears(years);setSubjects([]);setTopics([]);}).catch(e=>{if(e?.name!=='AbortError')setMessage(m.qbank.couldNotLoad);});return()=>controller.abort();},[examId,m.qbank.couldNotLoad]);
 const maxCount=mode==='exam' ? Math.min(300,catalog?.exam.product_max_items??300,catalog?.exam.official_max_items??300):Math.min(300,catalog?.exam.product_max_items??300); const effectiveCount=Math.min(count,maxCount);
 const topicOptions=useMemo(()=>{if(!catalog)return [];const list=subjects.length?catalog.topics_by_subject.filter(x=>subjects.includes(x.subject)).map(x=>x.topic):catalog.topics;return [...new Set(list)];},[catalog,subjects]);
 const changeSubjects=(next:string[])=>{const options=next.length?catalog?.topics_by_subject.filter(x=>next.includes(x.subject)).map(x=>x.topic)??[]:catalog?.topics??[];setSubjects(next);setTopics(selected=>selected.filter(topic=>options.includes(topic)));};


 useEffect(()=>{if(!catalog)return; const controller=new AbortController(); fetch('/api/qbank/pool-counts',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({examId,subjects,topics,reconstructionYear}),signal:controller.signal,cache:'no-store'}).then(async r=>{if(!r.ok)throw new Error();return r.json() as Promise<PoolCounts>;}).then(setPoolCounts).catch(()=>{if(!controller.signal.aborted)setPoolCounts(null);}); return()=>controller.abort();},[catalog,examId,subjects,topics,reconstructionYear]);
 const estimatedExamMinutes=useMemo(()=>catalog?Math.max(1,Math.ceil(effectiveCount/Math.max(1,catalog.exam.block_max_items))*catalog.exam.block_duration_minutes):0,[catalog,effectiveCount]);
 const officialTiming=Boolean(catalog?.exam.timing_verified && mode==='exam' && effectiveCount>=catalog?.exam.official_max_items);
 async function start(){setMessage(''); if(!examId||!catalog)return; if(effectiveCount<1||effectiveCount>maxCount)return; setBusy(true); try{const res=await fetch('/api/qbank/session/start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({examId,subjects,topics,questionCount:effectiveCount,mode,pool,reconstructionYear})});const body=await res.json().catch(()=>({})); if(!res.ok){setMessage(body.error==='insufficient_questions'?m.qbank.insufficient:body.error==='exam_question_limit'?m.qbank.examLimit:body.error==='account_inactive'?m.settings.accountSuspended:m.qbank.couldNotStart);return;} router.push(`/qbank/session/${body.sessionId}`);}catch{setMessage(m.qbank.couldNotStart);}finally{setBusy(false);}}
 return <section className="qbank-builder card card-pad">
   <div className="builder-head"><div><div className="kicker">{m.qbank.setupKicker}</div><h2>{m.qbank.setupTitle}</h2><p className="panel-sub">{m.qbank.setupSubtitle}</p></div><a className="btn" href="/qbank/history">{m.qbank.history}</a></div>
   <div className="builder-grid">
     <label className="field"><span>{m.qbank.exam}</span><select value={examId} onChange={e=>{setMessage('');setPoolCounts(null);setReconstructionYear(null);setCatalog(null);setSubjects([]);setTopics([]);setExamId(e.target.value);}}>{exams.map(e=><option key={e.id} value={e.id}>{e.code} — {e.name}</option>)}</select></label>
     <label className="field"><span>{reconstructionCopy.label}</span><select value={reconstructionYear ?? ''} onChange={e=>setReconstructionYear(e.target.value ? Number(e.target.value) : null)}><option value="">{reconstructionCopy.any}</option>{reconstructionYears.map(row=><option key={row.year} value={row.year}>שחזור {row.year} · {row.question_count}</option>)}</select><small className="field-note">{reconstructionCopy.hint}</small></label>
     <div className="field"><div className="field-label-row"><span>{m.qbank.subjectsLabel}</span><div className="filter-actions"><button className="btn btn-sm" type="button" onClick={()=>changeSubjects((catalog?.subjects??[]).map(s=>s.value))}>{m.common.all}</button><button className="btn btn-sm" type="button" onClick={()=>changeSubjects([])}>{m.common.clear}</button></div></div><div className="chip-grid">{(catalog?.subjects??[]).map(s=><label key={s.value} className={`filter-chip ${subjects.includes(s.value)?'selected':''}`}><input type="checkbox" checked={subjects.includes(s.value)} onChange={e=>changeSubjects(e.target.checked?[...subjects,s.value]:subjects.filter(x=>x!==s.value))}/><span>{subjectLabels[s.value]?.[locale]??s.label}</span></label>)}</div></div>
     <div className="field"><div className="field-label-row"><span>{m.qbank.topicsLabel}</span><div className="filter-actions"><button className="btn btn-sm" type="button" onClick={()=>setTopics(topicOptions)}>{m.common.all}</button><button className="btn btn-sm" type="button" onClick={()=>setTopics([])}>{m.common.clear}</button></div></div><div className="chip-grid compact">{topicOptions.length?topicOptions.map(t=><label key={t} className={`filter-chip ${topics.includes(t)?'selected':''}`}><input type="checkbox" checked={topics.includes(t)} onChange={e=>setTopics(v=>e.target.checked?[...v,t]:v.filter(x=>x!==t))}/><span>{t}</span></label>):<span className="form-hint">{m.qbank.noTopics}</span>}</div></div>
     <label className="field"><span>{m.qbank.questionCount}</span><div className="count-row"><input type="number" min={1} max={maxCount} value={effectiveCount} onChange={e=>setCount(Math.max(1,Math.min(maxCount,Number(e.target.value)||1)))}/><span className="field-note">{m.qbank.upTo300}{mode==='exam'?` · ${m.qbank.examCap} ${maxCount} · ${catalog?.exam.official_max_items} ${m.qbank.officialTiming}`:''}</span></div></label>
     <div className="field"><span>{m.qbank.mode}</span><div className="mode-switch"><button type="button" className={mode==='practice'?'active':''} onClick={()=>setMode('practice')}>{m.qbank.practiceMode}</button><button type="button" className={mode==='exam'?'active':''} onClick={()=>setMode('exam')}>{m.qbank.examMode}</button></div></div>
     <label className="field"><span>{m.qbank.pool}</span><select value={pool} onChange={e=>setPool(e.target.value as Pool)}><option value="mixed">{m.qbank.poolMixed} {poolCounts?`(${poolCounts.total})`:''}</option><option value="unseen">{m.qbank.poolUnseen} {poolCounts?`(${poolCounts.unseen})`:''}</option><option value="incorrect">{m.qbank.poolIncorrect} {poolCounts?`(${poolCounts.incorrect})`:''}</option><option value="answered">{m.qbank.poolAnswered} {poolCounts?`(${poolCounts.answered})`:''}</option><option value="unanswered">{m.qbank.poolUnanswered} {poolCounts?`(${poolCounts.unanswered})`:''}</option><option value="bookmarked">{m.qbank.poolBookmarked} {poolCounts?`(${poolCounts.bookmarked})`:''}</option></select></label>
   </div>
   {catalog&&<div className="exam-rules-strip"><span>{catalog.exam.code}</span><span>{m.qbank.realTime}: {mode==='exam' ? (officialTiming ? `${catalog.exam.total_duration_minutes} min · ${m.qbank.officialTiming}` : `${estimatedExamMinutes} min · ${m.qbank.scaledTiming}`) : m.qbank.noForcedTimer}</span><span>{m.qbank.blocks}: {Math.max(1,Math.min(catalog.exam.block_count,Math.ceil(effectiveCount/Math.max(1,catalog.exam.block_max_items))))}</span><span>{m.qbank.available}: {catalog.available_questions}</span></div>}
   {message&&<div className="form-message error">{message}</div>}
   <div className="builder-actions"><button type="button" className="btn btn-primary btn-lg" disabled={busy||!catalog||effectiveCount>maxCount} onClick={()=>void start()}>{busy?m.common.loading:m.qbank.startSession}</button><span className="panel-sub">{m.qbank.serverSelection}</span></div>
 </section>;
}
