-- Curated 2-3 word recall cues are stored by editors and reviewers, not generated by AI.
create or replace function public.set_question_key_terms(p_question_id uuid,p_terms text[])
returns void language plpgsql volatile security definer set search_path = '' as $$
declare v_terms text[]; v_status text;
begin
  if not public.has_permission('content.write') then raise exception 'forbidden'; end if;
  if p_terms is null then v_terms:='{}'; else
    select coalesce(array_agg(x order by ord),'{}') into v_terms from (
      select distinct left(trim(value),80) x, ord from unnest(p_terms) with ordinality t(value,ord)
      where nullif(trim(value),'') is not null order by ord limit 3
    ) q;
  end if;
  select workflow_status into v_status from public.questions where id=p_question_id;
  if v_status is null then raise exception 'question_not_found'; end if;
  update public.questions set key_terms=v_terms where id=p_question_id;
  update public.question_versions set key_terms=v_terms where question_id=p_question_id and version_no=(select max(version_no) from public.question_versions where question_id=p_question_id);
end;
$$;
revoke all on function public.set_question_key_terms(uuid,text[]) from public,anon; grant execute on function public.set_question_key_terms(uuid,text[]) to authenticated;
